"""
Django settings for patient_management project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import sys

print("Settings file location:", __file__)
print("Current working directory:", os.getcwd())
print("Python path:", sys.path)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
print("BASE_DIR:", BASE_DIR)

# Add the project root to the Python path
sys.path.insert(0, str(BASE_DIR))

# Create logs directory if it doesn't exist
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%p2466)5(%m8u#q_r!^1_u9grk_75s233z=$kulw@@v&jwg^s)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
print("DEBUG value set to:", DEBUG)

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '.loca.lt']

# Security settings - consolidated
SECURE_SSL_REDIRECT = False
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_HOST = None
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'
CSRF_COOKIE_SECURE = False  # Set to False for local development
SESSION_COOKIE_SECURE = False  # Set to False for local development

# Development-specific settings
if DEBUG:
    INTERNAL_IPS = ['127.0.0.1']
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
else:
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'patient_records',
    'csp',
]

# Import cache settings - using a try/except to handle potential import issues
try:
    from patient_management.settings.caching import CACHES, CACHE_KEYS, CACHE_TIMEOUTS, CACHE_VERSION
except ImportError as e:
    print(f"Warning: Could not import cache settings: {e}")
    # Fallback to basic local memory cache
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
        }
    }
    CACHE_KEYS = {}
    CACHE_TIMEOUTS = {}
    CACHE_VERSION = 1

# Session configuration
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'

# Existing session settings
SESSION_COOKIE_AGE = 3600  # Session expires after 1 hour (in seconds)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_SAMESITE = 'Lax'

# Cache configuration for static lookups
STATIC_CACHE_TIMEOUT = 3600  # 1 hour
STATIC_CACHE_KEY_PREFIX = 'static'

# Cache middleware settings
USE_CACHE_MIDDLEWARE = True
CACHE_MIDDLEWARE_SECONDS = 300
CACHE_MIDDLEWARE_KEY_PREFIX = 'patient_mgmt'

# Add cache middleware to the beginning of MIDDLEWARE
MIDDLEWARE = [
    'django.middleware.cache.UpdateCacheMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'patient_records.middleware.localtunnel.LocaltunnelBypassMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'patient_records.middleware.json_errors.JSONErrorMiddleware',
    'django.middleware.cache.FetchFromCacheMiddleware',
]

ROOT_URLCONF = 'patient_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'patient_management.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'patient_management',
        'USER': 'admin',
        'PASSWORD': 'admin',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Add these settings
LOGIN_REDIRECT_URL = 'home'
LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = 'login'

# Add these CSP settings
CSP_DEFAULT_SRC = (
    "'self'",
    "*.loca.lt",
)
CSP_SCRIPT_SRC = (
    "'self'",
    "'unsafe-inline'",
    "'unsafe-eval'",
    "'wasm-unsafe-eval'",
    "'inline-speculation-rules'",
    "*.loca.lt",
)
CSP_STYLE_SRC = (
    "'self'",
    "'unsafe-inline'",
    "*.loca.lt",
)
CSP_IMG_SRC = ("'self'", "data:", "blob:")
CSP_CONNECT_SRC = (
    "'self'",
    "*.loca.lt",
    "wss://*.loca.lt",
)
CSP_FONT_SRC = ("'self'", "data:")

# Add these settings for better security while allowing modal functionality
CSP_INCLUDE_NONCE_IN = ['script-src']
CSP_EXCLUDE_URL_PREFIXES = ('/admin/',)

STATICFILES_DIRS = [
    BASE_DIR / "patient_records/static",
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process} {thread} {message}\n'
                     'Path: {pathname}\n'
                     'Function: {funcName}\n'
                     'Details: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': 'logs/debug.log',
            'formatter': 'verbose',
            'maxBytes': 5242880,  # 5 MB
            'backupCount': 5,
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'patient_records': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'localtunnel': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.server': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

# Add these right after your LOGGING configuration
CSRF_TRUSTED_ORIGINS = [
    'https://*.loca.lt',
    'http://*.loca.lt',
    'http://localhost:8000',
    'http://127.0.0.1:8000'
]

# Proxy and timeout settings
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True
REQUEST_TIMEOUT = 120
KEEP_ALIVE_TIMEOUT = 120
WEBSOCKET_TIMEOUT = 120

# Static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Localtunnel settings
LOCALTUNNEL = {
    'BYPASS_HEADER': True,
}

# Session settings
SESSION_COOKIE_SAMESITE = 'Lax'

# End of settings file