# Generated by Django 5.1.2 on 2024-11-05 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDemographics',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('allergies', models.TextField(blank=True)),
                ('code_status', models.CharField(max_length=100)),
                ('poa_name', models.CharField(max_length=200)),
                ('relationship', models.CharField(max_length=100)),
                ('poa_contact', models.CharField(max_length=100)),
                ('veteran', models.BooleanField(default=False)),
                ('veteran_spouse', models.BooleanField(default=False)),
                ('marital_status', models.CharField(max_length=50)),
                ('street_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=10)),
                ('patient_phone', models.CharField(max_length=20)),
                ('patient_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('diagnosis', models.CharField(max_length=200)),
                ('icd_code', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_records.patientdemographics')),
            ],
        ),
    ]
