# Generated by Django 4.2.17 on 2025-02-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventstore',
            options={'ordering': ['timestamp']},
        ),
        migrations.RemoveIndex(
            model_name='eventstore',
            name='patient_rec_aggrega_0c74a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='eventstore',
            name='patient_rec_timesta_cebbb5_idx',
        ),
        migrations.AlterField(
            model_name='eventstore',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='eventstore',
            index=models.Index(fields=['aggregate_id', 'timestamp'], name='patient_rec_aggrega_9ba694_idx'),
        ),
        migrations.AddIndex(
            model_name='eventstore',
            index=models.Index(fields=['aggregate_type', 'timestamp'], name='patient_rec_aggrega_8b4821_idx'),
        ),
        migrations.AddIndex(
            model_name='eventstore',
            index=models.Index(fields=['event_type', 'timestamp'], name='patient_rec_event_t_5b97ca_idx'),
        ),
    ]
