# Generated by Django 5.1.2 on 2024-11-09 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBCLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('wbc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rbc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hemoglobin', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hematocrit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('platelets', models.DecimalField(decimal_places=2, max_digits=7)),
                ('mcv', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mch', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mchc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_records.patient')),
            ],
        ),
        migrations.CreateModel(
            name='CMPLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('sodium', models.DecimalField(decimal_places=2, max_digits=5)),
                ('potassium', models.DecimalField(decimal_places=2, max_digits=5)),
                ('chloride', models.DecimalField(decimal_places=2, max_digits=5)),
                ('co2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('glucose', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bun', models.DecimalField(decimal_places=2, max_digits=5)),
                ('creatinine', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calcium', models.DecimalField(decimal_places=2, max_digits=5)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_records.patient')),
            ],
        ),
    ]
