# Generated by Django 5.1.2 on 2024-11-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0002_cbclab_cmplab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cbclabs',
            name='erythrocyte_mcv',
        ),
        migrations.RemoveField(
            model_name='cmplabs',
            name='ag_ratio',
        ),
        migrations.RemoveField(
            model_name='cmplabs',
            name='alk_phos',
        ),
        migrations.RemoveField(
            model_name='cmplabs',
            name='alt',
        ),
        migrations.RemoveField(
            model_name='cmplabs',
            name='ast',
        ),
        migrations.RemoveField(
            model_name='cmplabs',
            name='globulin',
        ),
        migrations.AlterField(
            model_name='cbclabs',
            name='basophils',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cbclabs',
            name='eosinophils',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cbclabs',
            name='hematocrit',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cbclabs',
            name='hemoglobin',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cbclabs',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cbclabs',
            name='lymphocytes',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cbclabs',
            name='mch',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cbclabs',
            name='mchc',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cbclabs',
            name='mcv',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cbclabs',
            name='monocytes',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cbclabs',
            name='neutrophils',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cbclabs',
            name='platelets',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='cbclabs',
            name='rbc',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cbclabs',
            name='rdw',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cbclabs',
            name='wbc',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cmplabs',
            name='albumin',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cmplabs',
            name='bilirubin',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cmplabs',
            name='bun',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cmplabs',
            name='calcium',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cmplabs',
            name='chloride',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cmplabs',
            name='co2',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cmplabs',
            name='creatinine',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cmplabs',
            name='gfr',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cmplabs',
            name='glucose',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cmplabs',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cmplabs',
            name='potassium',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cmplabs',
            name='protein',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cmplabs',
            name='sodium',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
