# Generated by Django 4.2.19 on 2025-02-11 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0002_initial'),
    ]

    operations = [
    ]
