# Generated by Django 4.2.19 on 2025-02-12 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0003_auto_20250211_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='primary_provider',
            field=models.ForeignKey(blank=True, help_text='Primary healthcare provider for this patient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_patients', to='patient_records.provider'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['primary_provider'], name='patient_rec_primary_e3a10b_idx'),
        ),
    ]
