# Generated by Django 5.1.2 on 2024-11-09 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0003_remove_cbclabs_erythrocyte_mcv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmplab',
            name='patient',
        ),
        migrations.DeleteModel(
            name='CBCLab',
        ),
        migrations.DeleteModel(
            name='CMPLab',
        ),
    ]
