# Generated by Django 4.2.17 on 2025-02-02 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0004_auto_cleanup_phone_data'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='provider',
            name='patient_rec_date_269535_idx',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='date',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='zip',
        ),
        migrations.AddField(
            model_name='provider',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the provider is currently active'),
        ),
        migrations.AddField(
            model_name='provider',
            name='registration_date',
            field=models.DateField(default=datetime.date.today, help_text='Date when provider was registered in the system'),
        ),
        migrations.AddField(
            model_name='provider',
            name='zip_code',
            field=models.CharField(default='00000', help_text='US ZIP code (5 or 9 digits)', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provider',
            name='address',
            field=models.CharField(help_text='Street address', max_length=255),
        ),
        migrations.AlterField(
            model_name='provider',
            name='fax',
            field=models.CharField(blank=True, help_text='Format: XXX-XXX-XXXX', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone',
            field=models.CharField(default='000-000-0000', help_text='Format: XXX-XXX-XXXX', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provider',
            name='practice',
            field=models.CharField(help_text='Name of the medical practice', max_length=200),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider',
            field=models.CharField(help_text="Provider's full name", max_length=100),
        ),
        migrations.AlterField(
            model_name='provider',
            name='source',
            field=models.CharField(blank=True, help_text='Data source system', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='state',
            field=models.CharField(help_text='Two-letter US state code', max_length=2),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['-registration_date'], name='patient_rec_registr_e2c416_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['state'], name='patient_rec_state_09bc26_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['is_active'], name='patient_rec_is_acti_9fd158_idx'),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.CheckConstraint(check=models.Q(('state__regex', '^[A-Z]{2}$')), name='valid_state_code'),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.CheckConstraint(check=models.Q(('zip_code__regex', '^\\d{5}(-\\d{4})?$')), name='valid_zip_code'),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.CheckConstraint(check=models.Q(('phone__regex', '^\\d{3}-\\d{3}-\\d{4}$')), name='valid_phone'),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.CheckConstraint(check=models.Q(('fax__isnull', True), ('fax__regex', '^\\d{3}-\\d{3}-\\d{4}$'), _connector='OR'), name='valid_fax'),
        ),
    ]
