# Generated by Django 5.1.2 on 2024-11-06 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0004_remove_patient_current_medications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordrequestlog',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_records.patient'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_records.patient'),
        ),
        migrations.AlterField(
            model_name='adls',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_records.patient'),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_records.patient'),
        ),
        migrations.AlterField(
            model_name='occurrences',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_records.patient'),
        ),
        migrations.AlterField(
            model_name='cbclabs',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_records.patient'),
        ),
        migrations.AlterField(
            model_name='visits',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_records.patient'),
        ),
        migrations.AlterField(
            model_name='medications',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_records.patient'),
        ),
        migrations.AlterField(
            model_name='imaging',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_records.patient'),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_records.patient'),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_records.patient'),
        ),
        migrations.AlterField(
            model_name='cmplabs',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_records.patient'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='provider',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='provider',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='provider',
            name='zip',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='PatientDemographics',
        ),
    ]
