# Generated by Django 4.2.19 on 2025-02-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0004_patient_primary_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordrequestlog',
            name='due_date',
            field=models.DateField(blank=True, help_text='When records need to be provided', null=True),
        ),
        migrations.AddField(
            model_name='recordrequestlog',
            name='needs_attention',
            field=models.BooleanField(default=False, help_text='Whether this request needs immediate attention'),
        ),
        migrations.AddField(
            model_name='recordrequestlog',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the request', null=True),
        ),
        migrations.AddField(
            model_name='recordrequestlog',
            name='requester_name',
            field=models.CharField(blank=True, help_text='Name of person requesting records', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recordrequestlog',
            name='requester_organization',
            field=models.CharField(blank=True, help_text='Organization making the request', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recordrequestlog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('DENIED', 'Denied'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of the request', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventstore',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata about the event'),
        ),
        migrations.AddIndex(
            model_name='recordrequestlog',
            index=models.Index(fields=['status'], name='patient_rec_status_c25e9f_idx'),
        ),
        migrations.AddIndex(
            model_name='recordrequestlog',
            index=models.Index(fields=['due_date'], name='patient_rec_due_dat_679171_idx'),
        ),
        migrations.AddIndex(
            model_name='recordrequestlog',
            index=models.Index(fields=['needs_attention'], name='patient_rec_needs_a_ae7639_idx'),
        ),
    ]
