# Generated by Django 5.1.2 on 2024-11-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0004_remove_cmplab_patient_delete_cbclab_delete_cmplab'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'ordering': ['-date'], 'verbose_name_plural': 'diagnoses'},
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='source',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='icd_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
