# Generated by Django 5.1.3 on 2024-11-12 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0005_alter_diagnosis_options_remove_diagnosis_source_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medications',
            old_name='date',
            new_name='date_prescribed',
        ),
    ]
