# Generated by Django 5.1.3 on 2024-11-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0006_rename_date_medications_date_prescribed'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='medications',
            index=models.Index(fields=['-date_prescribed'], name='patient_rec_date_pr_b647ed_idx'),
        ),
        migrations.AddIndex(
            model_name='medications',
            index=models.Index(fields=['patient', '-date_prescribed'], name='patient_rec_patient_f8bd2a_idx'),
        ),
    ]
