# Generated by Django 5.1.3 on 2024-11-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0009_enhance_audit_trail'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='audittrail',
            new_name='patient_rec_patient_1553df_idx',
            old_name='audit_patient_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='audittrail',
            new_name='patient_rec_user_id_e05c33_idx',
            old_name='audit_user_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='audittrail',
            new_name='patient_rec_record__09f2aa_idx',
            old_name='audit_type_ts_idx',
        ),
        migrations.AlterField(
            model_name='audittrail',
            name='record_type',
            field=models.CharField(choices=[('PATIENT', 'Patient Demographics'), ('CLINICAL_NOTE', 'Clinical Notes'), ('CBC_LAB', 'CBC Lab Results'), ('CMP_LAB', 'CMP Lab Results'), ('MEDICATION', 'Medications'), ('SYMPTOM', 'Symptoms')], max_length=20),
        ),
    ]
