# Generated by Django 5.1.3 on 2024-11-17 21:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0010_rename_audit_patient_ts_idx_patient_rec_patient_1553df_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medications',
            name='dc_date',
            field=models.DateField(blank=True, null=True, verbose_name='Discontinue Date'),
        ),
        migrations.AlterField(
            model_name='medications',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medications',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medications',
            name='prn',
            field=models.BooleanField(default=False, verbose_name='PRN (As Needed)'),
        ),
    ]
