# Generated by Django 5.1.3 on 2024-11-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0012_audittrail_patient_identifier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audittrail',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveIndex(
            model_name='audittrail',
            name='patient_rec_patient_1553df_idx',
        ),
        migrations.RemoveIndex(
            model_name='audittrail',
            name='patient_rec_user_id_e05c33_idx',
        ),
        migrations.RemoveIndex(
            model_name='audittrail',
            name='patient_rec_record__09f2aa_idx',
        ),
        migrations.RemoveField(
            model_name='audittrail',
            name='ip_address',
        ),
        migrations.AlterField(
            model_name='audittrail',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10),
        ),
        migrations.AlterField(
            model_name='audittrail',
            name='record_type',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('VITALS', 'Vitals'), ('SYMPTOMS', 'Symptoms'), ('MEDICATIONS', 'Medications'), ('CMPLABS', 'CMP Labs'), ('CBCLABS', 'CBC Labs'), ('DIAGNOSIS', 'Diagnosis'), ('MEASUREMENTS', 'Measurements'), ('IMAGING', 'Imaging'), ('ADLS', 'ADLs'), ('OCCURRENCES', 'Occurrences'), ('CLINICALNOTES', 'Clinical Notes'), ('RECORDREQUESTLOG', 'Record Request Log')], max_length=20),
        ),
    ]
