# Generated by Django 5.1.3 on 2024-11-18 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0013_alter_audittrail_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittrail',
            name='patient_identifier',
            field=models.CharField(default='Unknown Patient', max_length=100),
        ),
        migrations.AlterField(
            model_name='audittrail',
            name='record_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['patient_identifier', '-timestamp'], name='patient_rec_patient_4f81e5_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['action', '-timestamp'], name='patient_rec_action_20d344_idx'),
        ),
    ]
