# Generated by Django 5.1.3 on 2024-11-20 04:31

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0014_alter_audittrail_patient_identifier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('overview', 'Overview'), ('clinical', 'Clinical Data'), ('history', 'History'), ('medications', 'Medications'), ('labs', 'Laboratory Results')], max_length=20)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='patient_records.patient')),
                ('referenced_adls', models.ManyToManyField(blank=True, related_name='referenced_in_notes', to='patient_records.adls')),
                ('referenced_cbc_labs', models.ManyToManyField(blank=True, related_name='referenced_in_notes', to='patient_records.cbclabs')),
                ('referenced_cmp_labs', models.ManyToManyField(blank=True, related_name='referenced_in_notes', to='patient_records.cmplabs')),
                ('referenced_diagnoses', models.ManyToManyField(blank=True, related_name='referenced_in_notes', to='patient_records.diagnosis')),
                ('referenced_imaging', models.ManyToManyField(blank=True, related_name='referenced_in_notes', to='patient_records.imaging')),
                ('referenced_medications', models.ManyToManyField(blank=True, related_name='referenced_in_notes', to='patient_records.medications')),
                ('referenced_occurrences', models.ManyToManyField(blank=True, related_name='referenced_in_notes', to='patient_records.occurrences')),
                ('referenced_symptoms', models.ManyToManyField(blank=True, related_name='referenced_in_notes', to='patient_records.symptoms')),
                ('referenced_visits', models.ManyToManyField(blank=True, related_name='referenced_in_notes', to='patient_records.visits')),
                ('referenced_vitals', models.ManyToManyField(blank=True, related_name='referenced_in_notes', to='patient_records.vitals')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
