# Generated by Django 5.1.3 on 2024-11-20 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0015_patientnote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientnote',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='patientnote',
            name='referenced_adls',
        ),
        migrations.RemoveField(
            model_name='patientnote',
            name='referenced_cbc_labs',
        ),
        migrations.RemoveField(
            model_name='patientnote',
            name='referenced_cmp_labs',
        ),
        migrations.RemoveField(
            model_name='patientnote',
            name='referenced_imaging',
        ),
        migrations.RemoveField(
            model_name='patientnote',
            name='referenced_medications',
        ),
        migrations.RemoveField(
            model_name='patientnote',
            name='referenced_occurrences',
        ),
        migrations.RemoveField(
            model_name='patientnote',
            name='referenced_symptoms',
        ),
        migrations.RemoveField(
            model_name='patientnote',
            name='referenced_visits',
        ),
        migrations.RemoveField(
            model_name='patientnote',
            name='tags',
        ),
        migrations.AddField(
            model_name='patientnote',
            name='referenced_labs',
            field=models.ManyToManyField(blank=True, to='patient_records.cmplabs'),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patientnote',
            name='category',
            field=models.CharField(choices=[('overview', 'Overview'), ('clinical', 'Clinical Data'), ('medications', 'Medications'), ('labs', 'Lab Results'), ('history', 'History')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patientnote',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_records.patient'),
        ),
        migrations.AlterField(
            model_name='patientnote',
            name='referenced_diagnoses',
            field=models.ManyToManyField(blank=True, to='patient_records.diagnosis'),
        ),
        migrations.AlterField(
            model_name='patientnote',
            name='referenced_vitals',
            field=models.ManyToManyField(blank=True, to='patient_records.vitals'),
        ),
    ]
