# Generated by Django 5.1.3 on 2024-11-20 05:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0016_alter_patientnote_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientnote',
            name='referenced_cbc_labs',
            field=models.ManyToManyField(blank=True, to='patient_records.cbclabs'),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='referenced_imaging',
            field=models.ManyToManyField(blank=True, to='patient_records.imaging'),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='referenced_medications',
            field=models.ManyToManyField(blank=True, to='patient_records.medications'),
        ),
        migrations.AddIndex(
            model_name='patientnote',
            index=models.Index(fields=['patient', '-updated_at'], name='patient_rec_patient_71d732_idx'),
        ),
        migrations.AddIndex(
            model_name='patientnote',
            index=models.Index(fields=['category', '-updated_at'], name='patient_rec_categor_f76191_idx'),
        ),
    ]
