# Generated by Django 5.1.3 on 2024-11-24 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0017_patientnote_referenced_cbc_labs_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientNote',
        ),
    ]
