# Generated by Django 5.1.3 on 2024-11-26 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0018_delete_patientnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordrequestlog',
            name='document_name',
        ),
        migrations.RemoveField(
            model_name='recordrequestlog',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='recordrequestlog',
            name='processed_date',
        ),
        migrations.RemoveField(
            model_name='recordrequestlog',
            name='received_on',
        ),
        migrations.RemoveField(
            model_name='recordrequestlog',
            name='requested_from',
        ),
        migrations.RemoveField(
            model_name='recordrequestlog',
            name='requested_via',
        ),
        migrations.RemoveField(
            model_name='recordrequestlog',
            name='status',
        ),
        migrations.AddField(
            model_name='adls',
            name='toileting',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adls',
            name='transferring',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient_records.provider'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imaging',
            name='body_part',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imaging',
            name='findings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurements',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='occurrences',
            name='action_taken',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recordrequestlog',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recordrequestlog',
            name='records_requested',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recordrequestlog',
            name='request_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recordrequestlog',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='symptoms',
            name='severity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visits',
            name='assessment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visits',
            name='chief_complaint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visits',
            name='plan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
