"""Constants for audit and event sourcing."""

# Aggregate Types
PATIENT_AGGREGATE = 'PATIENT'
CLINICAL_AGGREGATE = 'CLINICAL'
PROVIDER_AGGREGATE = 'PROVIDER'

# Patient Events
PATIENT_REGISTERED = 'PATIENT_REGISTERED'
PATIENT_UPDATED = 'PATIENT_UPDATED'
PATIENT_ARCHIVED = 'PATIENT_ARCHIVED'

# Clinical Events
VITALS_RECORDED = 'VITALS_RECORDED'
VITALS_UPDATED = 'VITALS_UPDATED'
LAB_RESULTS_ADDED = 'LAB_RESULTS_ADDED'
LAB_RESULTS_UPDATED = 'LAB_RESULTS_UPDATED'
SYMPTOMS_ADDED = 'SYMPTOMS_ADDED'
SYMPTOMS_UPDATED = 'SYMPTOMS_UPDATED'
DIAGNOSIS_ADDED = 'DIAGNOSIS_ADDED'
DIAGNOSIS_UPDATED = 'DIAGNOSIS_UPDATED'
VISIT_RECORDED = 'VISIT_RECORDED'
VISIT_UPDATED = 'VISIT_UPDATED'
MEASUREMENT_RECORDED = 'MEASUREMENT_RECORDED'
MEASUREMENT_UPDATED = 'MEASUREMENT_UPDATED'
IMAGING_ADDED = 'IMAGING_ADDED'
IMAGING_UPDATED = 'IMAGING_UPDATED'
ADLS_RECORDED = 'ADLS_RECORDED'
ADLS_UPDATED = 'ADLS_UPDATED'
OCCURRENCE_RECORDED = 'OCCURRENCE_RECORDED'
OCCURRENCE_UPDATED = 'OCCURRENCE_UPDATED'
NOTE_CREATED = 'NOTE_CREATED'
NOTE_UPDATED = 'NOTE_UPDATED'
NOTE_DELETED = 'NOTE_DELETED'
MEDICATION_ADDED = 'MEDICATION_ADDED'
MEDICATION_UPDATED = 'MEDICATION_UPDATED'
MEDICATION_DISCONTINUED = 'MEDICATION_DISCONTINUED'

# Provider Events
PROVIDER_REGISTERED = 'PROVIDER_REGISTERED'
PROVIDER_UPDATED = 'PROVIDER_UPDATED'
PROVIDER_DEACTIVATED = 'PROVIDER_DEACTIVATED'

# Record Request Events
RECORD_REQUESTED = 'RECORD_REQUESTED'
RECORD_REQUEST_FULFILLED = 'RECORD_REQUEST_FULFILLED'
RECORD_REQUEST_DENIED = 'RECORD_REQUEST_DENIED'

# Audit Actions
CREATE = 'CREATE'
UPDATE = 'UPDATE'
DELETE = 'DELETE'

# Record Types
PATIENT_RECORD = 'PATIENT'
VITALS_RECORD = 'VITALS'
LAB_RECORD = 'LAB'
NOTE_RECORD = 'NOTE'
MEASUREMENT_RECORD = 'MEASUREMENT'
SYMPTOM_RECORD = 'SYMPTOM'
IMAGING_RECORD = 'IMAGING'
ADLS_RECORD = 'ADLS'
OCCURRENCE_RECORD = 'OCCURRENCE'
PROVIDER_RECORD = 'PROVIDER'
RECORD_REQUEST = 'RECORD_REQUEST' 